#' @keywords internal
"_PACKAGE"

## usethis namespace: start

#' @importFrom arrow binary
#' @importFrom arrow bool
#' @importFrom arrow boolean
#' @importFrom arrow date32
#' @importFrom arrow date64
#' @importFrom arrow dictionary
#' @importFrom arrow float16
#' @importFrom arrow float32
#' @importFrom arrow float64
#' @importFrom arrow halffloat
#' @importFrom arrow int16
#' @importFrom arrow int32
#' @importFrom arrow int64
#' @importFrom arrow int8
#' @importFrom arrow large_utf8
#' @importFrom arrow open_dataset
#' @importFrom arrow schema
#' @importFrom arrow string
#' @importFrom arrow time32
#' @importFrom arrow time64
#' @importFrom arrow timestamp
#' @importFrom arrow uint16
#' @importFrom arrow uint32
#' @importFrom arrow uint64
#' @importFrom arrow uint8
#' @importFrom arrow utf8
#' @importFrom arrow write_dataset
#' @importFrom callr rscript
#' @importFrom digest digest
#' @importFrom dplyr anti_join
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr collect
#' @importFrom dplyr copy_to
#' @importFrom dplyr count
#' @importFrom dplyr db_list_tables
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr rows_append
#' @importFrom dplyr rows_delete
#' @importFrom dplyr rows_insert
#' @importFrom dplyr rows_update
#' @importFrom dplyr rows_upsert
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr slice
#' @importFrom dplyr slice_max
#' @importFrom dplyr slice_min
#' @importFrom dplyr summarise
#' @importFrom dplyr tbl
#' @importFrom dplyr ungroup
#' @importFrom lubridate as_date
#' @importFrom lubridate as_datetime
#' @importFrom lubridate as.duration
#' @importFrom lubridate as.period
#' @importFrom lubridate now
#' @importFrom lubridate parse_date_time
#' @importFrom plyr rbind.fill
#' @importFrom pryr object_size
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_df
#' @importFrom purrr partial
#' @importFrom purrr pmap
#' @importFrom purrr walk
#' @importFrom readr read_csv
#' @importFrom rlang empty_env
#' @importFrom rlang is_empty
#' @importFrom rlang sym
#' @importFrom rlang syms
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr expand_grid
#' @importFrom tidyr nest
#' @importFrom tidyr unite
#' @importFrom yaml read_yaml
#' @importFrom yaml write_yaml
## usethis namespace: end
NULL
